# Generated by Django 5.2.3 on 2026-08-06 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AartiBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('devotee_name', models.CharField(max_length=150, verbose_name='Devotee Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('aarti_type', models.CharField(choices=[('mangala', 'Mangala Aarti (6:00 AM)'), ('rajbhog', 'Rajbhog Aarti (12:00 PM)'), ('sandhya', 'Sandhya Aarti (7:00 PM)'), ('shej', 'Shej Aarti (9:30 PM)')], max_length=30, verbose_name='Aarti Type')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('number_of_devotees', models.PositiveIntegerField(default=1, verbose_name='Number of Devotees')),
                ('id_proof_image', models.ImageField(blank=True, null=True, upload_to='aarti_bookings/id_proofs/', verbose_name='ID Proof Image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Special Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Aarti Booking',
                'verbose_name_plural': 'Aarti Bookings',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='contact/attachments/', verbose_name='Attachment Image')),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=150, verbose_name='Donor Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (INR)')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Transaction ID')),
                ('payment_method', models.CharField(choices=[('upi', 'UPI / QR Code'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash Offering')], default='upi', max_length=30, verbose_name='Payment Method')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='donations/receipts/', verbose_name='Receipt Screenshot')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified & Processed'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(choices=[('darshan', 'Live Darshan'), ('rituals', 'Pooja & Rituals'), ('decorations', 'Temple Decoration'), ('events', 'Mahotsav Events'), ('general', 'General')], default='darshan', max_length=50, verbose_name='Category')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('caption', models.TextField(blank=True, verbose_name='Caption / Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('membership_tier', models.CharField(choices=[('silver', 'Silver Bhakta'), ('gold', 'Gold Bhakta'), ('platinum', 'Platinum Trustee'), ('life', 'Life Patron')], default='silver', max_length=30, verbose_name='Membership Tier')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memberships/photos/', verbose_name='Member Photo')),
                ('address', models.TextField(blank=True, verbose_name='Residential Address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
