# Generated by Django 5.2.3 on 2026-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aartibooking',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='aartibooking',
            name='aarti_type',
            field=models.CharField(choices=[('morning', 'Morning Aarti (9:00 AM)'), ('night', 'Night Aarti (8:00 PM)'), ('mangala', 'Mangala Aarti (6:00 AM)'), ('rajbhog', 'Rajbhog Aarti (12:00 PM)'), ('sandhya', 'Sandhya Aarti (7:00 PM)'), ('shej', 'Shej Aarti (9:30 PM)')], default='morning', max_length=30, verbose_name='Aarti Type'),
        ),
        migrations.AlterField(
            model_name='aartibooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='confirmed', max_length=20, verbose_name='Status'),
        ),
    ]
