# Generated by Django 5.2.3 on 2026-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aartibooking_city_alter_aartibooking_aarti_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='membership',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='membership',
            name='volunteer',
            field=models.CharField(blank=True, default='Aarti & Ritual Assistance', max_length=100, verbose_name='Volunteer Interest'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('approved', 'Approved'), ('pending', 'Pending Approval'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
