# Generated by Django 5.2.3 on 2026-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membership_city_membership_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('GPay / UPI', 'GPay / UPI'), ('upi', 'UPI / QR Code'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash Offering')], default='GPay / UPI', max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified / Success'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
