# Generated by Django 5.2.3 on 2026-08-26 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donation_email_alter_donation_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('day', models.CharField(max_length=100, verbose_name='Day / Date Tag')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('time', models.CharField(blank=True, default='', max_length=100, verbose_name='Time')),
                ('location', models.CharField(blank=True, default='Main Temple Hall', max_length=200, verbose_name='Location')),
                ('banner_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Banner URL')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Festival Event',
                'verbose_name_plural': 'Festival Events',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
