# Generated by Django 6.0.6 on 2026-08-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Celebration Schedule', 'verbose_name_plural': 'Celebration Schedule'},
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Ritual', 'Ritual & Pooja'), ('Aarti', 'Aarti & Darshan'), ('Mahaprasad', 'Mahaprasad & Bhog'), ('Cultural', 'Cultural & Music'), ('Procession', 'Procession & Visarjan'), ('General', 'General')], default='Ritual', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Day / Date Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active / Inactive'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Time (Display)'),
        ),
    ]
