# Generated by Django 5.2.3 on 2026-08-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Celebration Schedule', 'verbose_name_plural': 'Celebration Schedule'},
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='Sacred Rituals', help_text='e.g. Sacred Rituals, Maha Aarti, Prasad Offering, Visarjan', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, default='', help_text='e.g. 11:30 AM', max_length=50, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, default='', help_text='e.g. 08:30 AM', max_length=50, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(help_text='e.g. Day 01 | Bhadrapada Chaturthi or 2026-09-14', max_length=100, verbose_name='Date / Day Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active / Inactive'),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Determines zig-zag timeline position: 1=Left, 2=Right, 3=Left, 4=Right...', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, default='', help_text='e.g. 08:30 AM - 11:30 AM or 12:30 PM onwards', max_length=100, verbose_name='Time (Display)'),
        ),
    ]
