# Generated by Django 5.2.3 on 2026-08-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_options_event_category_event_date_and_more'),
        ('core', '0006_alter_event_options_event_category_event_end_time_and_more'),
    ]

    operations = [
    ]
