# Generated by Django 5.2.3 on 2026-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260830_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Ritual', 'Ritual & Pooja'), ('Aarti', 'Aarti & Darshan'), ('Mahaprasad', 'Mahaprasad & Bhog'), ('Cultural', 'Cultural & Music'), ('Procession', 'Procession & Visarjan'), ('General', 'General')], default='Ritual', help_text='e.g. Sacred Rituals, Maha Aarti, Prasad Offering, Visarjan', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, default='', help_text='e.g. Day 01 | Bhadrapada Chaturthi or 2026-09-14', max_length=100, verbose_name='Date / Day Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, default='', help_text='e.g. 11:30 AM', max_length=50, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, default='', help_text='e.g. 08:30 AM', max_length=50, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, default='', help_text='e.g. 08:30 AM - 11:30 AM or 12:30 PM onwards', max_length=100, verbose_name='Time (Display)'),
        ),
    ]
